target_vars:
  - "hones16"
  - "emoti16"
  - "extra16"
  - "agree16"
  - "consc16"
  - "openn16"
model:
  backbone: "big-bird-roberta-base"
  backbone_aggregation: "cls"
  name: "joint-reg"
  arch:
    non_linearity: "relu"
    hidden_layers:
      - 384
      - 96
      - 32
training:
  validation_split: 0.8
  num_epochs: 100
  batch_size: 32
  criterion: "mse"
  optimizer:
    name: "adam"
    learning_rate: 0.001
  early_stopping:
    monitor: "mse"
    patience: 5
  checkpoint_frequency: 10
